---
product: "1.0.0"
info:
  name: "product1"
  title: "Product1"
  version: "1.0.0"
visibility:
  view:
    enabled: true
    type: "public"
    tags: []
    orgs: []
  subscribe:
    enabled: true
    type: "authenticated"
    tags: []
    orgs: []
apis:
  invoke:
    $ref: "invoke_1.0.0.yaml"
  swiggy:
    $ref: "swiggy_1.0.0.yaml"
  youtube:
    $ref: "youtube_1.0.0.yaml"
  facebook:
    $ref: "facebook_1.0.0.yaml"
  google:
    $ref: "google_1.0.0.yaml"
plans:
  Default:
    title: "Default Plan"
